### PR TITLE
Create computercraft-server.toml

### PR DESCRIPTION
**Pull request by Ki-Tan2934**
Remove File upload Security concern with CC-tweaked HTTP Access to server files

### CODE REVIEW

**Review by thevortex — APPROVED** [review]

**Comment by tomodachi94** [comment]
Potentially related: https://github.com/AllTheMods/ATM-7/pull/1182 https://github.com/AllTheMods/ATM-7/pull/1048

**Comment by 9551-Dev** [comment]
What security concern is here? CC tweaked is completely secure. There isnt really anything bad you can do with HTTP enabled (thats why its like that by default.)

local ips are already blocked by CCT so there should be no issue with keeping HTTP enabled

**Comment by enigmaquip** [comment]
We, the team, feel that non minecraft related traffic should be OPT-IN and not OPT-OUT and as such try to limit those interactions without conscious decision to activate them. Recent posts have since made us aware of our oversight in this pack with regards to this config.

**Comment by tomodachi94** [comment]
> We, the team, feel that non minecraft related traffic should be OPT-IN and not OPT-OUT and as such try to limit those interactions without conscious decision to activate them.

What about the HTTP API is opt-out? If a user invokes the `pastebin` command, for example, that's a user decision, no?

**Comment by enigmaquip** [comment]
And the server operator? This is already a hashed out conversation that is not going to be revisited past this point

**Comment by Apethesis** [comment]
CC Computers are sandboxed, i doubt the server operator should care about what happens on them unless something is causing lag.

**Comment by walksanatora** [comment]
Also this does not patch out file upload to server

**Comment by walksanatora** [comment]
You would have to *patch the jar* to remove file uploads
As it is not managed by a config
You could remove the programs that do it be default (import.lua and shell.lua)
But you can easily re-write import.lua

**Pull request merged**
